// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGj1mpIeGrNtrWSgjYeeVgehlVdAOfXY',
    appId: '1:118976941053:web:2d2f577291fe92db7ea794',
    messagingSenderId: '118976941053',
    projectId: 'mytodo-cc5ca',
    authDomain: 'mytodo-cc5ca.firebaseapp.com',
    storageBucket: 'mytodo-cc5ca.appspot.com',
    measurementId: 'G-3P46D05CMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsx9fiwLrtUjFXYZaqYabiOY5_cNBe31o',
    appId: '1:118976941053:android:6d0f7d5ef6effaf97ea794',
    messagingSenderId: '118976941053',
    projectId: 'mytodo-cc5ca',
    storageBucket: 'mytodo-cc5ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaUv6tynbjRIdouLczmBwlWvdCm6mL5dM',
    appId: '1:118976941053:ios:c43b85887729fb617ea794',
    messagingSenderId: '118976941053',
    projectId: 'mytodo-cc5ca',
    storageBucket: 'mytodo-cc5ca.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaUv6tynbjRIdouLczmBwlWvdCm6mL5dM',
    appId: '1:118976941053:ios:80319759bb1bbca47ea794',
    messagingSenderId: '118976941053',
    projectId: 'mytodo-cc5ca',
    storageBucket: 'mytodo-cc5ca.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
